project:
  type: book

book:
  title: "Minicurso TRI - Abave 2025"
  author: "Alexandre Jaloto"
  date: "08/09/2025"
  chapters:
    - index.qmd
    - analise_2pl.qmd
    - analise_graded.qmd

format:
  html:
    theme: cosmo
